### ISSUE TITLE
My project of a similar scope: App-Notifier-*

### ISSUE THREAD

**Issue by shlomif** [shaoeric/pyprompt#1]
Hi!

See https://bitbucket.org/shlomif/app-notifier/src/default/ and http://blogs.perl.org/users/shlomi_fish/2012/07/announcement-the-app-notifier-cpan-distributions.html . This is a simple HTTP-based system for client-server notifications. I wonder if we can collaborate.

**Comment by shaoeric** [comment]
i'd love to, but i have not learned about perl. how can i help you

**Comment by shlomif** [comment]
@shaoeric : one option would be to have an option for pynotice to invoke "notifier notify" using subprocess.py or similar. See https://metacpan.org/pod/distribution/App-Notifier-Client/bin/notifier . Note that there are also https://wiki.archlinux.org/index.php/Desktop_notifications .

**Comment by shaoeric** [comment]
means i need to invoke your perl program "notifier notify" as api? if so, i need some time to learn some perl

**Comment by shlomif** [comment]
@shaoeric : no, you can use https://docs.python.org/3/library/subprocess.html or similar to invoke it as it is a bona fide executable. See https://en.wikipedia.org/wiki/Fork%E2%80%93exec .

**Comment by shaoeric** [comment]
got that, and what shall i do next,

**Comment by shlomif** [comment]
@shaoeric :

> got that, and what shall i do next,

what do you mean?

**Comment by shaoeric** [comment]
sorry, i am just a Chinese student, not good at english.
i wonder how can i get your execution, and contribute to the project?

**Comment by shlomif** [comment]
@shaoeric : I'll send a pull req.

**Comment by shaoeric** [comment]
i have merged app-notifier into pynotice, but i develop pynotice on win64, does  app-notifier run on linux? i cannot invoke app-notifier directly. here is the prompt of error: OSError:[WinError 193] %1 not effective Win32 application.
you can test it  using demo/main.py on "test" branch

**Comment by shlomif** [comment]
> i have merged app-notifier into pynotice, but i develop pynotice on win64, does app-notifier run on linux? i cannot invoke app-notifier directly. here is the prompt of error: OSError:[WinError 193] %1 not effective Win32 application.
> you can test it using demo/main.py on "test" branch

I admit I have only tested app-notifier on Linux so far, but I intend it to run on MSWindows as well. How did you install it?

**Comment by shaoeric** [comment]
i have thought it can be run as .sh file. Could you help me test if it can work?

**Comment by shlomif** [comment]
> i have thought it can be run as .sh file. Could you help me test if it can work?

Please see http://strawberryperl.com/ - it is perl 5 - not shell and there is https://metacpan.org/pod/ExtUtils::PL2Bat .

**Comment by shaoeric** [comment]
i have installed App::Notifier::Cliendt::Notifier_app and strawberryperl,  but here is an error:
Can't open '\.app_notifier.yml' for input:
No such file or directory at D:/StrawberryPerl/perl/vendor/lib/YAML/XS.pm line 48.

**Comment by shaoeric** [comment]
but after careful consideration, i am so sorry i may not continue this work, because i just want to develop a simple and interesting module with python instead of a complicated program. So sorry!

**Comment by shlomif** [comment]
@shaoeric : the integration already works fairly well here, so it is ok. Closing - thanks!
